In [ ]:
spark.version

'4.1.0'

In [ ]:
## taking data from API and storing it in a pandas dataframe

import pandas as pd
import requests

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=IBM&apikey=*********'
r = requests.get(url)
data = r.json()



ts = data["Weekly Time Series"]

df = pd.DataFrame.from_dict(ts, orient="index")
df.index.name = "date"

df.reset_index(inplace=True)
df

            date   1. open   2. high    3. low  4. close 5. volume
0     2026-06-22  249.0600  253.3100  243.8100  252.5500   8916651
1     2026-06-18  272.0000  276.6200  243.6800  249.1000  34253212
2     2026-06-12  286.4400  290.5000  266.5000  272.2400  34602931
3     2026-06-05  322.5500  332.4600  281.0701  284.8400  86135011
4     2026-05-29  254.5500  300.9999  245.4500  297.8000  59445527
...          ...       ...       ...       ...       ...       ...
1385  1999-12-10  113.0000  122.1200  107.5600  109.0000  58626000
1386  1999-12-03  104.9400  112.8700  102.1200  111.8700  37670000
1387  1999-11-26  105.5000  109.8700  101.8100  105.0000  37165600
1388  1999-11-19   96.0000  105.1200   92.6200  103.9400  61550800
1389  1999-11-12   90.5000   97.5000   90.5000   95.8700  43569700

[1390 rows x 6 columns]

In [ ]:
access_key = "*************"
secret_key = "*************"
bucket = "stock1data1lake1garv"

In [ ]:
df_test = spark.read.csv(f"s3a://{bucket}/")
print("S3 Access works!")

S3 Access works!

In [ ]:
spark_df = spark.createDataFrame(df)

In [ ]:
spark_df

DataFrame[date: string, 1. open: string, 2. high: string, 3. low: string, 4. close: string, 5. volume: string]

In [ ]:
# writing as CSV
import datetime as dt


## this is for the file naming with date
fileappend = str(dt.datetime.now().date())
print(fileappend)


spark_df.write.mode("overwrite").option("header","true").option("fs.s3a.access.key", access_key).option("fs.s3a.secret.key", secret_key).option("fs.s3a.endpoint", "s3.amazonaws.com").csv(f"s3a://{bucket}/raw/ibm-{fileappend}")

print(f"Data written for {fileappend} to S3 successfully!")

################# Temp data writing....

2026-06-22
Data written for 2026-06-22 to S3 successfully!

In [ ]:
# Reading data directly from S3 WITH credentials
df = spark.read\
    .option("fs.s3a.access.key", access_key)\
    .option("fs.s3a.secret.key", secret_key)\
    .option("fs.s3a.endpoint", "s3.amazonaws.com")\
    .option("header", "true")\
    .csv(f"s3a://{bucket}/raw/ibm-{fileappend}")

display(df)

date,1. open,2. high,3. low,4. close,5. volume
2016-07-01,146.1800,152.9700,142.5000,152.3500,19155814
2016-06-24,152.6000,155.4800,146.1800,146.5900,22214411
2016-06-17,151.6300,152.7200,149.0000,151.9900,15849580
2016-06-10,153.0900,154.0900,151.8600,152.3700,14920842
2016-06-03,152.5600,153.8100,151.5400,152.8900,13470239
2016-05-27,147.6100,152.9300,146.6600,152.8400,14910875
2016-05-20,147.6500,149.9900,143.9550,147.2500,16406443
2016-05-13,147.7000,151.0900,147.0100,147.7200,17034303
2016-05-06,146.5600,147.9700,142.9000,147.2900,21059912
2016-04-29,148.1600,150.7800,144.1910,145.9400,16956550
2016-04-22,151.7500,153.1400,142.6100,148.5000,37688644
2016-04-15,150.2600,152.7600,148.5800,151.7200,17443203
2016-04-08,152.3400,153.5200,147.8100,149.3500,18417556
2016-04-01,147.7500,153.1000,147.2300,152.5200,20439783
2016-03-24,147.3000,149.2800,144.4900,147.9500,17611709
2016-03-18,142.0100,147.5100,141.0400,147.0900,29886417
2016-03-11,137.2800,142.9236,136.8718,142.3600,23556160
2016-03-04,132.0000,139.4200,130.9000,137.8000,22557187
2016-02-26,133.8400,134.9200,129.6800,132.0300,20763400
2016-02-19,121.8300,134.0000,121.3400,133.0800,23958762
2016-02-12,126.0000,127.5100,116.9010,121.0400,32025579
2016-02-05,124.4000,128.6400,122.2900,128.5700,25527891
2016-01-29,122.1000,124.7900,120.6500,124.7900,27278749
2016-01-22,130.1100,132.1000,118.0000,122.5000,44203492
2016-01-15,131.8100,134.2799,128.8700,130.0300,29470082
2016-01-08,135.6000,136.8900,131.3200,131.6300,25251873
2015-12-31,137.7400,140.4400,136.5400,137.6200,13538507
2015-12-24,135.8300,139.3050,134.0200,138.2500,16540309
2015-12-18,135.3100,139.6500,134.0200,134.9000,27823388
2015-12-11,140.1600,140.4100,133.9100,134.5700,21354563
2015-12-04,138.6100,141.4000,137.9900,140.4300,22935841
2015-11-27,138.5300,139.3400,137.1200,138.4600,13199481
2015-11-20,131.7900,138.9150,131.7900,138.5000,21083793
2015-11-13,137.9200,138.0800,131.6500,131.7500,25069755
2015-11-06,140.5000,142.8000,137.8700,138.2500,21526383
2015-10-30,144.7500,145.0000,137.3300,140.0800,34698762
2015-10-23,149.8500,149.9700,139.3000,144.6800,42068316
2015-10-16,152.4000,152.5800,148.5800,150.3900,17455488
2015-10-09,145.8200,153.1470,145.8200,152.3900,19465122
2015-10-02,144.4200,145.7100,140.5600,144.5800,19914471
2015-09-25,145.3900,146.9800,141.9500,145.4200,16815584
2015-09-18,147.3700,149.6800,143.9800,144.5100,20721826
2015-09-11,145.8600,149.0400,144.5100,147.3700,13916382
2015-09-04,147.2600,148.4000,141.8500,143.7000,21421138
2015-08-28,143.4700,148.9700,140.6200,147.9800,32508092
2015-08-21,155.2000,156.6900,148.7000,148.8500,19846207
2015-08-14,156.7700,157.4652,153.9500,155.7500,17165086
2015-08-07,161.7000,161.8500,154.3350,155.1200,20138504
2015-07-31,159.0000,162.0600,158.5000,161.9900,15380412
2015-07-24,172.7900,173.7800,159.4100,159.7500,37075256
2015-07-17,167.9300,172.5200,167.5200,172.5100,17138495
2015-07-10,163.8300,167.4000,162.2317,166.9500,18143986
2015-07-02,163.9200,165.6100,162.1200,165.0900,12979210
2015-06-26,167.6500,169.9700,165.2300,165.4600,20939777
2015-06-19,165.3300,168.7200,164.2500,166.9900,20761376
2015-06-12,167.1700,170.4400,163.3700,166.9900,18364270
2015-06-05,170.2100,171.5601,167.2000,167.4000,13868111
2015-05-29,172.1100,172.4800,169.1300,169.6500,12435919
2015-05-22,173.4400,174.4400,171.9300,172.2200,11939607
2015-05-15,172.6500,174.4100,168.8400,173.2600,13435074
2015-05-08,174.4700,176.3000,168.8600,172.6800,16793441
2015-05-01,170.8900,175.1303,170.0200,173.6700,21874751
2015-04-24,162.1000,171.9100,161.9000,169.7800,35436301
2015-04-17,162.3700,164.9600,160.0300,160.6700,17532781
2015-04-10,159.6900,163.8400,158.7020,162.8600,13917063
2015-04-02,161.3100,163.6000,158.3900,160.4500,16765545
2015-03-27,162.7700,165.3500,158.9100,160.4000,23569213
2015-03-20,155.0500,163.0000,154.8000,162.8800,25684872
2015-03-13,158.2000,161.1500,153.4000,154.2800,26135448
2015-03-06,161.6800,161.8900,158.0600,158.5000,21117049
2015-02-27,164.2300,164.9900,159.7700,161.9400,22941227
2015-02-20,159.7500,164.4900,159.7300,163.6500,14108892
2015-02-13,156.0000,160.8000,155.0800,160.4000,18164756
2015-02-06,154.0000,158.7100,151.5100,156.7200,22439830
2015-01-30,158.2600,159.4600,149.5200,153.3100,32927307
2015-01-23,156.7000,157.6000,151.0700,155.8700,31230797
2015-01-16,159.0000,159.9700,153.7400,157.1400,23272056
2015-01-09,161.2700,161.2700,154.0300,159.1100,24440360
2015-01-02,162.0000,163.3100,159.4500,162.0600,15698987
2014-12-26,158.3300,163.0900,158.3300,162.3400,12508916
2014-12-19,155.9300,160.4100,150.5000,158.5100,34588770
2014-12-12,163.2900,163.3300,155.3300,155.3800,23397756
2014-12-05,161.6400,164.5200,161.3500,163.2700,20945441
2014-11-28,161.5400,163.8600,161.0100,162.1700,17053892
2014-11-21,164.1600,164.9700,159.8000,160.9200,22273217
2014-11-14,161.9000,164.4900,161.6100,164.1600,20088151
2014-11-07,164.2500,164.5400,160.0500,162.0700,20603321
2014-10-31,162.0000,165.5900,161.8000,164.4000,27342119
2014-10-24,166.8450,170.3310,161.1000,162.0800,69701346
2014-10-17,185.4900,186.6500,178.6900,182.0500,24355568
2014-10-10,189.6900,190.8900,185.1000,185.9300,15795271
2014-10-03,188.5100,190.8500,186.2400,188.6700,14352364
2014-09-26,193.7200,194.1400,188.6100,190.0600,16209901
2014-09-19,191.4200,195.0000,190.5800,194.0000,20044000
2014-09-12,190.7500,192.7800,189.5100,191.2800,12878100
2014-09-05,192.6800,192.9700,190.0600,191.2000,9627700
2014-08-29,191.3900,194.1330,190.6600,192.3000,11487700
2014-08-22,188.1000,192.0700,187.7600,190.4100,11074800
2014-08-15,187.8100,188.8800,186.2800,187.3800,10927100
2014-08-08,189.3500,189.9500,183.5800,186.6300,14770900
2014-08-01,194.3000,196.4000,188.8600,189.1500,19838900
2014-07-25,191.3000,195.9000,189.2500,194.4000,19580700
2014-07-18,188.5500,195.9500,188.2100,192.5000,34217100
2014-07-11,187.6100,188.9000,186.2100,188.0000,14983700
2014-07-03,181.3300,188.9900,180.2600,188.5300,18382300
2014-06-27,181.9200,183.0000,179.2700,181.7100,17703900
2014-06-20,182.4000,184.4700,181.2350,181.5500,24186800
2014-06-13,186.2200,187.6400,180.9100,182.5600,18143900
2014-06-06,184.7600,187.6500,183.9200,186.3700,14243300
2014-05-30,184.8000,185.6500,182.3300,184.3600,15895800
2014-05-23,186.6100,187.1600,184.7000,185.9400,14066100
2014-05-16,191.1200,193.0300,185.9300,187.0600,19407200
2014-05-09,191.0500,191.4900,186.9300,190.0800,13925300
2014-05-02,191.1400,196.8600,190.5800,191.4400,21195300
2014-04-25,189.8000,193.0000,189.1100,189.6300,22312800
2014-04-17,196.2400,198.7100,187.0100,190.0100,30565200
2014-04-11,191.7200,199.2100,191.5700,195.1900,30598500
2014-04-04,191.6400,195.1300,191.2800,191.7700,29036500
2014-03-28,187.4300,195.6300,187.3700,190.4500,35465000
2014-03-21,182.6600,188.7000,182.6600,186.6700,30821100
2014-03-14,187.5500,188.4500,182.2100,182.2100,24057200
2014-03-07,183.3300,188.9200,182.8200,187.6800,20103400
2014-02-28,182.8200,186.1200,182.8200,185.1700,20734000
2014-02-21,183.1800,185.7100,182.3200,182.7900,19774200
2014-02-14,176.9700,184.4300,176.2500,183.6900,21312600
2014-02-07,176.0200,177.5600,172.1900,177.2500,25234000
2014-01-31,179.6050,179.6500,175.3400,176.6800,25559900
2014-01-24,190.2300,190.3900,179.6400,179.6400,38736900
2014-01-17,186.2600,190.8100,183.8600,190.0900,27635300
2014-01-10,187.1500,190.3500,185.3000,187.2600,22947500
2014-01-03,185.3200,187.7900,184.6700,186.6400,15248000
2013-12-27,181.0500,186.5000,180.6100,185.0800,12400800
2013-12-20,173.2200,182.0000,172.7300,180.0200,32267100
2013-12-13,177.9900,178.1520,172.7300,172.8000,21870800
2013-12-06,179.4600,179.5900,175.1600,177.6700,24816100
2013-11-29,180.2500,180.7600,177.3100,179.6800,20384900
2013-11-22,183.5200,186.2400,179.9200,181.3000,25637400
2013-11-15,180.1900,184.0487,179.6600,183.1900,25682800
2013-11-08,179.9000,181.3900,177.3500,179.9900,25635300
2013-11-01,177.0400,182.3200,176.2000,179.2300,25853600
2013-10-25,174.4200,179.1000,172.6301,176.8500,29861500
2013-10-18,185.4100,186.9900,172.5700,173.7800,45663100
2013-10-11,181.8500,186.2300,178.7100,186.1600,20859700
2013-10-04,185.5600,186.7400,183.0000,184.1000,16351900
2013-09-27,190.0600,192.4100,186.4500,186.9200,15079700
2013-09-20,193.7000,194.8900,190.0200,190.0200,22379100
2013-09-13,183.6800,193.1000,183.3100,192.1700,18194900
2013-09-06,183.6300,185.0000,182.3100,183.0300,11856200
2013-08-30,185.2700,187.0000,181.1000,182.2700,15052200
2013-08-23,185.3000,186.5700,183.1685,185.4200,14564700
2013-08-16,186.9700,189.9900,185.3400,185.3400,16580500
2013-08-09,195.1600,195.8800,186.7900,187.8200,20128300
2013-08-02,196.8300,197.8300,193.2215,195.1600,15338600
2013-07-26,193.4000,197.8300,193.2804,197.3500,14719100
2013-07-19,192.4200,200.9400,191.6800,193.5400,31679400
2013-07-12,195.6000,195.7800,190.7800,192.0700,20715900
2013-07-05,192.1500,195.1600,190.2600,194.9300,12378100
2013-06-28,193.9900,196.9000,188.4100,191.1100,25092600
2013-06-21,203.4400,206.0900,193.5401,195.4600,22773400
2013-06-14,206.9700,206.9800,200.3400,202.2000,14580500
2013-06-07,208.2500,210.0500,201.4700,206.3500,17768500
2013-05-31,207.4400,211.9800,206.0400,208.0200,16799600
2013-05-24,208.0200,210.1500,204.4200,205.7200,20259100
2013-05-17,204.1800,209.5000,202.0400,208.4400,21587300
2013-05-10,203.7900,205.0000,201.5200,204.4700,18700700
2013-05-03,194.7800,205.3190,194.6500,204.5100,26809200
2013-04-26,191.1500,195.1700,187.6800,194.3100,27976600
2013-04-19,210.4400,212.0000,189.7600,190.0000,35696400
2013-04-12,209.0700,213.0900,207.3300,211.3800,15273700
2013-04-05,212.8000,214.8900,206.3400,209.4100,16247600
2013-03-28,212.5400,213.4400,209.7350,213.3000,12516100
2013-03-22,212.9000,215.8200,210.1100,212.0800,18085500
2013-03-15,210.0400,215.9000,209.0400,214.9200,23433000
2013-03-08,202.5900,210.7400,202.5500,210.3800,18680900
2019-11-01,136.0000,136.6300,133.2000,135.5300,16136475
2019-10-25,132.6100,135.9300,130.9000,135.4400,19388201
2019-10-18,142.3100,143.7200,132.2500,134.0900,34208011
2019-10-11,142.2600,144.5000,138.2500,142.7600,14096608
2019-10-04,143.7300,147.3500,139.1800,142.9900,15911420
2019-09-27,141.1900,145.0900,140.5600,143.2400,12376163
2019-09-20,142.5600,145.0300,140.5100,141.8800,15262993
2019-09-13,140.5900,145.4600,140.4600,143.6700,17776693
2019-09-06,134.8500,141.7000,133.3300,140.5700,12663912
2019-08-30,131.0500,136.0700,129.1600,135.5300,16211916
2019-08-23,134.8800,136.3300,128.8300,129.5700,16504912
2019-08-16,135.6600,136.5700,130.2500,133.7600,20933133
2019-08-09,144.9800,145.1000,135.3500,136.1300,28623442
2019-08-02,151.1100,152.9500,145.5900,147.2500,22876887
2019-07-26,150.1600,151.9400,148.3800,151.3600,16794485
2019-07-19,142.8900,151.5800,141.9500,149.6800,31893327
2019-07-12,141.0500,142.9200,139.1300,142.7400,13194248
2019-07-05,139.6000,141.8200,139.2800,141.3800,9862722
2019-06-28,139.2000,140.1500,137.8400,137.9000,15575818
2019-06-21,135.3900,139.5400,134.7000,139.2000,15851123
2019-06-14,134.3800,136.4600,133.9100,135.1500,13722199
2019-06-07,127.1000,134.7200,127.0600,133.3100,16193845
2019-05-31,132.1300,132.6400,126.8500,126.9900,14869322
2019-05-24,133.5300,137.0600,130.4400,132.2800,15557532
2019-05-17,133.2800,136.1100,130.9600,134.3200,16426011
2019-05-10,138.3000,140.6900,132.4200,135.3200,19509963
2019-05-03,139.1500,141.8100,138.6800,140.2500,16772230
2019-04-26,139.4200,141.3100,137.7100,139.4400,16961387
2019-04-18,144.4000,145.3900,136.2600,140.3300,27390537
2019-04-12,143.0200,144.4400,141.8400,144.3500,13675882
2019-04-05,141.5100,144.2200,141.5100,143.2800,14574262
2019-03-29,139.0600,141.2200,138.3500,141.1000,14257045
2019-03-22,139.8300,142.1200,138.7200,139.4500,17883337
2019-03-15,136.0300,140.3300,135.8400,139.4300,20959826
2019-03-08,139.9900,140.0800,133.5800,135.0900,18558647
2019-03-01,140.0000,140.4900,137.7200,139.2000,15273342
2019-02-22,137.8100,139.3800,137.2200,139.2500,13238819
2019-02-15,134.2900,138.1900,133.9100,138.0300,17299173
2019-02-08,134.0200,136.6500,132.1200,133.7100,21874687
2019-02-01,133.1000,135.4100,132.5800,134.1000,23585862
2019-01-25,123.3000,135.0000,121.5400,133.9700,44147478
2019-01-18,120.5100,124.7200,119.7600,123.8200,23616108
2019-01-11,117.5000,121.8600,116.6700,121.4600,19780844
2019-01-04,113.3300,117.4900,111.6900,117.3200,18047093
2018-12-28,109.9000,114.8000,105.9400,113.0300,21630293
2018-12-21,119.0700,120.2700,110.4400,110.9400,39485288
2018-12-14,119.7400,123.8100,118.5200,119.9000,23701178
2018-12-07,125.6700,126.5900,118.8700,119.3400,25801474
2018-11-30,118.3700,124.6900,118.0600,124.2700,27471124
2018-11-23,121.6300,122.1800,116.7000,117.1900,18035587
2018-11-16,123.5000,123.5700,119.5100,121.5700,23510061
2018-11-09,116.1000,125.0600,116.0000,123.5400,48482997
2018-11-02,119.3400,123.9500,114.0900,115.6700,87773431
2018-10-26,129.5800,131.9000,123.7100,124.7900,36964774
2018-10-19,140.3800,145.4500,127.9600,129.1000,50928336
2018-10-12,148.5000,149.0700,138.7800,140.8500,27703434
2018-10-05,151.7100,154.3600,147.8700,149.0300,18943237
2018-09-28,151.1000,153.3500,148.3600,151.2100,22847744
2018-09-21,148.4400,152.6000,147.4700,151.3500,37327961
2018-09-14,146.6000,149.3000,145.2500,148.3300,20298346
2018-09-07,145.9800,147.6600,144.8100,145.4500,15394651
2018-08-31,146.9400,147.9300,145.2500,146.4800,15929583
2018-08-24,146.3700,147.1600,144.7500,146.0400,12992907
2018-08-17,144.1500,146.3900,142.0000,146.0600,17890077
2018-08-10,146.9500,147.6400,143.8800,144.4800,17100909
2018-08-03,144.8000,147.9200,142.3300,147.7000,24366161
2018-07-27,146.3500,149.2700,144.6600,145.1500,19940363
2018-07-20,145.6700,150.5400,142.7400,146.3500,36572622
2018-07-13,142.5900,146.9800,142.4700,145.9000,17395351
2018-07-06,138.2800,142.9400,138.2000,142.4800,12024030
2018-06-29,140.4000,141.3600,137.4500,139.7000,25451478
2018-06-22,144.1800,144.5200,140.7800,141.2800,21004666
2018-06-15,146.6200,147.5200,143.7000,145.3900,21311072
2018-06-08,142.3000,146.7000,142.1800,146.1400,18618365
2018-06-01,142.5300,143.1000,140.2100,141.9500,20343954
2018-05-25,144.9500,146.2000,142.9500,143.6400,16951460
2018-05-18,144.4700,145.1900,142.9200,144.0800,16304020
2018-05-11,144.0000,144.8500,141.2800,144.1400,20021856
2018-05-04,146.8600,147.3800,139.9000,143.9100,23464605
2018-04-27,145.0300,147.3600,144.1100,146.4800,25028049
2018-04-20,157.9900,162.0000,144.5100,144.9000,51127683
2018-04-13,151.8000,159.2200,151.7400,156.7100,21372171
2018-04-06,153.3400,154.9200,147.4500,150.5700,20949699
2018-03-29,151.2100,154.8700,150.2800,153.4300,14934365
2018-03-23,159.7100,159.8900,148.5400,148.8900,21959274
2018-03-16,159.6400,162.1100,157.7400,160.2600,25076217
2018-03-09,154.1200,159.5800,153.7500,159.3100,22842811
2018-03-02,155.8100,159.7800,151.8800,154.4900,18831762
2018-02-23,155.7900,156.7900,152.7900,155.5200,14987102
2018-02-16,150.9000,157.7900,149.6400,156.1800,25701914
2018-02-09,157.8900,158.5000,144.4000,149.5100,38856237
2018-02-02,167.4500,168.3900,158.8700,159.0300,21842492
2018-01-26,161.5100,168.7200,161.1100,167.3400,28170112
2018-01-19,165.1000,171.1300,161.3000,162.3700,51246304
2018-01-12,162.6600,164.9400,161.7000,163.1400,22376145
2018-01-05,154.5000,162.9000,153.5400,162.4900,26160206
2017-12-29,152.5100,154.7200,152.5000,153.4200,10573732
2017-12-22,153.4100,154.1800,151.4900,152.5000,20045931
2017-12-15,154.9700,157.8500,152.0300,152.5000,31101402
2017-12-08,155.6700,156.8000,153.2600,154.8100,20236835
2017-12-01,152.0600,155.0200,151.6200,154.7600,24386604
2017-11-24,150.6400,152.4500,149.9000,151.8400,13728716
2017-11-17,148.8800,150.1500,146.2110,148.9700,23731918
2017-11-10,151.7700,151.8200,149.1400,149.1600,21891991
2017-11-03,153.7600,154.9300,151.4900,151.5800,19467703
2017-10-27,162.0500,162.5100,152.9110,153.6800,28529638
2017-10-20,147.2200,162.4800,146.1800,162.0700,56148944
2017-10-13,146.5000,148.9500,146.3500,147.1000,16128636
2017-10-06,145.3500,147.5400,145.2100,146.4800,12252293
2017-09-29,145.1200,147.4200,144.2100,145.0800,18131168
2017-09-22,144.8100,145.8911,144.2200,145.1300,16890140
2017-09-15,143.5400,146.3800,143.0100,144.8200,24882951
2017-09-08,143.5000,144.6400,141.6400,142.4500,13803467
2017-09-01,144.1100,144.5600,141.9000,144.0800,17765494
2017-08-25,139.5900,144.1900,139.1300,143.7400,15927109
2017-08-18,142.0000,143.3400,139.5800,139.7000,18585485
2017-08-11,145.0000,145.0900,141.1900,141.8400,18161288
2017-08-04,144.3800,145.6700,144.1700,145.1600,16503121
2017-07-28,147.0000,147.4900,143.6400,144.2900,21206630
2017-07-21,153.5900,154.2900,146.5100,147.0800,39223438
2017-07-14,152.9100,154.6150,152.0500,154.2400,15015697
2017-07-07,153.5800,156.0250,152.1400,152.9400,11462576
2017-06-30,154.7100,155.7500,153.1400,153.8300,13465670
2017-06-23,155.5100,155.8600,153.3900,154.1100,18294998
2017-06-16,154.1900,157.2000,152.9400,155.3800,23761609
2017-06-09,151.8200,154.2650,150.8000,154.1000,20653101
2017-06-02,151.9500,153.2000,151.5900,152.0500,13583558
2017-05-26,152.1000,153.7300,151.2300,152.4900,14563625
2017-05-19,150.6200,154.1400,150.1100,151.9800,23606431
2017-05-12,152.8000,153.4700,149.7900,150.3700,28432713
2017-05-05,160.0500,160.4200,153.0000,155.0500,28746997
2017-04-28,161.2900,162.0400,159.6300,160.2900,22585454
2017-04-21,169.7500,171.6900,159.6000,160.3800,41444548
2017-04-13,172.5300,172.5600,168.9800,169.5300,15162492
2017-04-07,173.8200,176.3300,171.2800,172.1400,20657952
2017-03-31,172.6900,175.0000,172.0937,174.1400,15949938
2017-03-24,175.6500,176.2300,172.8000,173.8300,16816026
2017-03-17,177.8500,179.0000,174.7500,175.6500,20678038
2017-03-10,179.7200,181.2900,175.8800,177.8300,18283618
2017-03-03,181.1900,182.5500,179.2800,180.0500,14713309
2017-02-24,180.6000,182.5000,179.1200,181.3500,13082284
2017-02-17,179.2400,182.7900,178.3500,180.6700,15587334
2017-02-10,175.3100,178.8701,174.3800,178.6800,15458288
2017-02-03,176.9800,177.0700,172.8900,175.8200,16952754
2017-01-27,170.0800,179.2500,170.0100,177.3000,24898161
2017-01-20,166.6900,170.6400,165.8000,170.5500,26891514
2017-01-13,169.4700,169.8000,165.3400,167.3400,16710843
2017-01-06,167.0000,169.9200,166.0100,169.5300,11943248
2016-12-30,166.9800,167.9800,165.5000,165.9900,7770697
2016-12-23,166.8300,168.2500,165.2500,166.7100,13209502
2016-12-16,166.7200,169.9520,165.0700,166.7300,23953742
2016-12-09,160.8500,166.7200,158.9300,166.5200,17154330
2016-12-02,163.2000,164.6600,158.3000,160.0200,19370850
2016-11-25,160.6900,163.1900,160.3697,163.1400,11269212
2016-11-18,161.2500,161.8600,157.5500,160.3900,16168917
2016-11-11,153.9900,161.3400,151.0000,161.2700,25292112
2016-11-04,152.7600,154.3300,151.6700,152.4300,15168515
2016-10-28,150.4000,154.4400,149.8300,152.6100,16009359
2016-10-21,154.4500,155.8900,147.7900,149.6300,31731091
2016-10-14,156.7100,158.4900,152.2700,154.4500,15614452
2016-10-07,158.0600,158.5300,154.8600,155.6700,11417766
2016-09-30,154.4600,165.0000,153.4600,158.8500,15801644
2016-09-23,154.8700,157.2200,153.8700,154.9800,12476162
2016-09-16,155.2600,158.5300,153.2100,153.8400,21990587
2016-09-09,159.8800,161.7600,155.6500,155.6900,15009419
2016-09-02,158.8300,160.5700,158.1000,159.5500,11286596
2016-08-26,160.0000,161.3400,157.8500,158.3200,13571765
2016-08-19,162.4000,162.9700,159.5200,160.0400,14873739
2016-08-12,162.7300,164.9500,161.5200,161.9500,19554950
2016-08-05,160.6500,163.5100,159.8000,163.5000,15067283
2016-07-29,162.0000,163.6000,160.0300,160.6200,13747991
2016-07-22,159.3000,162.1700,157.8900,162.0700,24775973
2016-07-15,154.6000,161.4000,154.5000,159.7800,18535456
2016-07-08,151.1900,154.6000,149.9200,154.4600,10213227
2023-03-03,131.4200,131.8700,127.7100,129.6400,17865677
2023-02-24,134.0000,134.3850,128.8600,130.5700,14198950
2023-02-17,136.0000,137.3900,133.8900,135.0200,16543870
2023-02-10,135.8300,136.7400,133.3400,135.6000,22140989
2023-02-03,134.3200,136.9500,132.8000,136.9400,27874571
2023-01-27,141.4000,142.9850,132.9800,134.3900,43345140
2023-01-20,146.4200,147.1800,139.7500,141.2000,21419368
2023-01-13,144.0800,146.6600,142.9000,145.8900,14580596

In [ ]:
df.printSchema()

root
 |-- date: string (nullable = true)
 |-- 1. open: string (nullable = true)
 |-- 2. high: string (nullable = true)
 |-- 3. low: string (nullable = true)
 |-- 4. close: string (nullable = true)
 |-- 5. volume: string (nullable = true)

In [ ]:
import pandas as pd 
import numpy as np 

df = df.toPandas()
df.head(6)

         date   1. open   2. high    3. low  4. close 5. volume
0  2016-07-01  146.1800  152.9700  142.5000  152.3500  19155814
1  2016-06-24  152.6000  155.4800  146.1800  146.5900  22214411
2  2016-06-17  151.6300  152.7200  149.0000  151.9900  15849580
3  2016-06-10  153.0900  154.0900  151.8600  152.3700  14920842
4  2016-06-03  152.5600  153.8100  151.5400  152.8900  13470239
5  2016-05-27  147.6100  152.9300  146.6600  152.8400  14910875

In [ ]:
df.describe()

              date   1. open   2. high    3. low  4. close 5. volume
count         1390      1390      1390      1390      1390      1390
unique        1390      1264      1310      1298      1291      1387
top     2016-07-01  113.0000  195.0000  101.0000  104.0000  18700700
freq             1         5         3         4         3         2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       1390 non-null   object
 1   1. open    1390 non-null   object
 2   2. high    1390 non-null   object
 3   3. low     1390 non-null   object
 4   4. close   1390 non-null   object
 5   5. volume  1390 non-null   object
dtypes: object(6)
memory usage: 65.3+ KB

In [ ]:
df.isnull().sum()

date         0
1. open      0
2. high      0
3. low       0
4. close     0
5. volume    0
dtype: int64

In [ ]:
df = df.dropna()
df = df.drop_duplicates()

In [ ]:
df

            date   1. open   2. high    3. low  4. close 5. volume
0     2016-07-01  146.1800  152.9700  142.5000  152.3500  19155814
1     2016-06-24  152.6000  155.4800  146.1800  146.5900  22214411
2     2016-06-17  151.6300  152.7200  149.0000  151.9900  15849580
3     2016-06-10  153.0900  154.0900  151.8600  152.3700  14920842
4     2016-06-03  152.5600  153.8100  151.5400  152.8900  13470239
...          ...       ...       ...       ...       ...       ...
1385  2003-04-11   82.6000   82.9000   78.1300   78.7500  39935800
1386  2003-04-04   79.2600   83.4800   78.1200   80.7900  46339300
1387  2003-03-28   82.4600   84.0000   80.5000   80.8500  42576300
1388  2003-03-21   78.0000   84.9000   77.8400   84.9000  58133300
1389  2003-03-14   77.4500   79.4800   73.1700   79.0000  48104400

[1390 rows x 6 columns]

In [ ]:
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       1390 non-null   datetime64[ns]
 1   1. open    1390 non-null   object
 2   2. high    1390 non-null   object
 3   3. low     1390 non-null   object
 4   4. close   1390 non-null   object
 5   5. volume  1390 non-null   object
dtypes: datetime64[ns](1), object(5)
memory usage: 65.3+ KB

In [ ]:
from pandas import to_numeric

df['1. open'] = pd.to_numeric(df['1. open'])
df['2. high'] = pd.to_numeric(df['2. high'])
df['3. low'] = pd.to_numeric(df['3. low'])
df['4. close'] = pd.to_numeric(df['4. close'])
df['5. volume'] = pd.to_numeric(df['5. volume'])

df = df.sort_values(by='date').reset_index(drop=True)

##Feature Engineering

In [ ]:
# daily return by closing price with python fuc pct_change = percentage change from previous close
df["daily return"] = df['4. close'].pct_change()*100
df['daily return'] = df['daily return'].round(2)

# price range
df['price range'] = df['2. high'] - df['3. low']
df['price range'] = df['price range'].round(2)

# moving average by 5days 
df['ma5'] = df['4. close'].rolling(window=5).mean()
df['ma5'] = df['ma5'].round(2)

# moving average by 20days 
df['ma20'] = df['4. close'].rolling(window=20).mean()
df['ma20'] = df['ma20'].round(2)

print('\n ===New Feature Added===')
df['open'] = df['1. open']
df['high'] = df['2. high']
df['low'] = df['3. low']
df['close'] = df['4. close']
df['volume'] = df['5. volume']

 ===New Feature Added===

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1390 non-null   datetime64[ns]
 1   1. open       1390 non-null   float64
 2   2. high       1390 non-null   float64
 3   3. low        1390 non-null   float64
 4   4. close      1390 non-null   float64
 5   5. volume     1390 non-null   int64
 6   daily return  1389 non-null   float64
 7   price range   1390 non-null   float64
 8   ma5           1386 non-null   float64
 9   ma20          1371 non-null   float64
 10  open          1390 non-null   float64
 11  high          1390 non-null   float64
 12  low           1390 non-null   float64
 13  close         1390 non-null   float64
 14  volume        1390 non-null   int64
dtypes: datetime64[ns](1), float64(12), int64(2)
memory usage: 163.0 KB

In [ ]:
df.drop(columns=['1. open','2. high','3. low','4. close','5. volume'],inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1390 non-null   datetime64[ns]
 1   daily return  1389 non-null   float64
 2   price range   1390 non-null   float64
 3   ma5           1386 non-null   float64
 4   ma20          1371 non-null   float64
 5   open          1390 non-null   float64
 6   high          1390 non-null   float64
 7   low           1390 non-null   float64
 8   close         1390 non-null   float64
 9   volume        1390 non-null   int64
dtypes: datetime64[ns](1), float64(8), int64(1)
memory usage: 108.7 KB

In [ ]:
df = df[['date','open','high','low','close','volume','daily return','price range','ma5','ma20']]

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1390 non-null   datetime64[ns]
 1   open          1390 non-null   float64
 2   high          1390 non-null   float64
 3   low           1390 non-null   float64
 4   close         1390 non-null   float64
 5   volume        1390 non-null   int64
 6   daily return  1389 non-null   float64
 7   price range   1390 non-null   float64
 8   ma5           1386 non-null   float64
 9   ma20          1371 non-null   float64
dtypes: datetime64[ns](1), float64(8), int64(1)
memory usage: 108.7 KB

## Statistics & Insights

In [ ]:
print(f'Total days: {len(df)}')
print(f'Date range: {df['date'].min()} to {df['date'].max()}')
print(f'Average close price: ${df['close'].mean().round(2)}')
print(f'Highest close price: ${df['close'].max()}')
print(f'Lowest close price: ${df['close'].min()}')

Total days: 1390
Date range: 1999-11-12 00:00:00 to 2026-06-22 00:00:00
Average close price: $139.76
Highest close price: $309.24
Lowest close price: $56.6

In [ ]:
print(f'\n Average daily return: {df['daily return'].mean().round(2)}%')
print(f' Highest daily return: {df['daily return'].max().round(2)}%')
print(f' Lowest daily return: {df['daily return'].min().round(2)}%')
print(f'\n Volatility (STD): {df['daily return'].std().round(2)}%')

 Average daily return: 0.14%
 Highest daily return: 19.37%
 Lowest daily return: -15.49%

 Volatility (STD): 3.64%

## Finding Outliers

In [ ]:
threshold = 5

outliers = df[
    (df['daily return'] > threshold) | 
    (df['daily return'] < -threshold)
]

print(f'\n ===> Days with unusual returns (> {threshold}%')
print(f'\n Total number of outliears entries are {len(outliers)}')

 ===> Days with unusual returns (> 5%

 Total number of outliears entries are 180

### Logging number of processed rows

In [ ]:
from datetime import datetime
import json

run_time = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

try:
    rows_processed = int(df.shape[0])
    status = "SUCCESS"
    error_msg = ""
except Exception as e :
    rows_processed = 0
    status = "FAILED"
    error_msg = str(e)

log_entry = {
        "run_time" : run_time,
        "rows_processed" : rows_processed,
        "status" : status,
        "error_msg" : error_msg
}

log_path = f"s3a://{bucket}/logs/log_{run_time.replace(' ','_').replace(':','-')}.json"
spark.createDataFrame([log_entry]).coalesce(1).write.mode('overwrite') \
                .option('fs.s3a.access.key', access_key).option('fs.s3a.secret.key', secret_key).option('fs.s3a.endpoint','s3.amazonaws.com').json(log_path)

print(f'Log saved to {log_path}')
print(f'Rows {rows_processed} processed | Time: {run_time}')

/home/spark-d4a7e445-97fa-48aa-8790-ae/.ipykernel/9609/command-5679939643889279-814625950:4: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  run_time = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

Log saved to s3a://stock1data1lake1garv/logs/log_2026-06-22_20-39-27.json
Rows 1390 processed | Time: 2026-06-22 20:39:27

In [ ]:
df_final = spark.createDataFrame(df)

df_final.write.mode('overwrite')\
    .option('header','true').option('fs.s3a.access.key', access_key).option('fs.s3a.secret.key', secret_key).option('fs.s3a.endpoint','s3.amazonaws.com').csv(f's3a://{bucket}/processed/stock_cleaned-{fileappend}/',header=True)

print('clean data saved to S3!!!')

clean data saved to S3!!!

In [ ]:
df_final.createOrReplaceTempView('stock')

### Monthly Average Closing Price

In [ ]:
spark.sql('''
          select month(date) as month, 
          round(avg(close),2) as avg_close
          from stock
          group by month
          order by month
          ''').show()

+-----+---------+
|month|avg_close|
+-----+---------+
|    1|   142.21|
|    2|   141.99|
|    3|    140.9|
|    4|   139.64|
|    5|   142.64|
|    6|   141.26|
|    7|   137.95|
|    8|   138.72|
|    9|   137.89|
|   10|   138.67|
|   11|   137.33|
|   12|   137.95|
+-----+---------+

### Monthly Trading Volume

In [ ]:
spark.sql("""
        select 
            month(date) as month,
            sum(volume) as total_volume
            from stock
            group by month
            order by month 
        """).show()

+-----+------------+
|month|total_volume|
+-----+------------+
|    1|  3707867831|
|    2|  3001278754|
|    3|  3686273855|
|    4|  3630509837|
|    5|  3214330708|
|    6|  3094719926|
|    7|  3258101067|
|    8|  2766345213|
|    9|  2791813831|
|   10|  3912203909|
|   11|  3118181928|
|   12|  3081195761|
+-----+------------+

### Highest Closing Price Per Month

In [ ]:
spark.sql("""
            select 
                month(date) as month,
                MAX(close)as highset_close
            from stock 
            group by month
            order by month 
            """).show()

+-----+-------------+
|month|highset_close|
+-----+-------------+
|    1|        306.7|
|    2|       298.93|
|    3|       261.54|
|    4|       253.47|
|    5|        297.8|
|    6|        289.7|
|    7|       291.97|
|    8|       250.05|
|    9|       284.31|
|   10|       307.46|
|   11|       308.58|
|   12|       309.24|
+-----+-------------+

### Most Volatile Month

In [ ]:
spark.sql('''
          select 
                month(date) as month,
                round(avg(`price range`),2) as avg_volatility
                from stock 
                group by month
                order by avg_volatility desc ''').show()

+-----+--------------+
|month|avg_volatility|
+-----+--------------+
|   10|          8.26|
|    4|          7.73|
|    1|          7.56|
|    3|          6.76|
|    2|          6.67|
|    5|          6.63|
|    6|          6.36|
|    7|          6.22|
|   11|           6.1|
|    9|          5.57|
|   12|          5.38|
|    8|          5.37|
+-----+--------------+

### AVG Daily Return By Month

In [ ]:
spark.sql("""
          select 
                month(date) as month,
                round(avg(`daily return`),2) as avg_return
                from stock 
                group by month
                order by month
          """).show()

+-----+----------+
|month|avg_return|
+-----+----------+
|    1|      0.75|
|    2|     -0.34|
|    3|       0.3|
|    4|     -0.12|
|    5|      0.36|
|    6|     -0.33|
|    7|      0.55|
|    8|     -0.19|
|    9|      0.03|
|   10|     -0.07|
|   11|      0.56|
|   12|      0.09|
+-----+----------+

### TOP 10 Trading Days

In [ ]:
spark.sql("""
          select 
                date,
                `daily return`
                from stock 
                order by `daily return` desc
                limit 10 """).show()

+-------------------+------------+
|               date|daily return|
+-------------------+------------+
|2001-04-20 00:00:00|       19.37|
|2001-01-19 00:00:00|       18.59|
|2026-05-29 00:00:00|       17.32|
|2002-10-18 00:00:00|       16.16|
|2026-05-22 00:00:00|       15.75|
|2009-07-17 00:00:00|       14.47|
|2020-04-09 00:00:00|       14.26|
|2025-01-31 00:00:00|       13.75|
|2008-10-31 00:00:00|       13.28|
|2020-03-27 00:00:00|       13.25|
+-------------------+------------+

### Monthly Performance Dashboard Query

In [ ]:
spark.sql("""
          select 
                month(date) as month,
                round(avg(close),2) as avg_close,
                sum(volume) as total_volume,
                round(avg(`daily return`),4) as avg_return,
                round(avg(`price range`),2) as avg_volatility
            from stock
            group by month
            order by month""").show()

+-----+---------+------------+----------+--------------+
|month|avg_close|total_volume|avg_return|avg_volatility|
+-----+---------+------------+----------+--------------+
|    1|   142.21|  3707867831|     0.754|          7.56|
|    2|   141.99|  3001278754|    -0.342|          6.67|
|    3|    140.9|  3686273855|    0.2967|          6.76|
|    4|   139.64|  3630509837|   -0.1222|          7.73|
|    5|   142.64|  3214330708|    0.3647|          6.63|
|    6|   141.26|  3094719926|   -0.3299|          6.36|
|    7|   137.95|  3258101067|    0.5531|          6.22|
|    8|   138.72|  2766345213|    -0.191|          5.37|
|    9|   137.89|  2791813831|    0.0322|          5.57|
|   10|   138.67|  3912203909|   -0.0684|          8.26|
|   11|   137.33|  3118181928|    0.5638|           6.1|
|   12|   137.95|  3081195761|    0.0866|          5.38|
+-----+---------+------------+----------+--------------+